name: Auto-merge Patch/Minor PRs

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
    branches: [main, master]

jobs:
  automerge:
    if: |
      github.actor == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Renovate PRs with auto-merge label
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
