name: Auto-merge Renovate PRs

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened, ready_for_review]
    branches: [main, master]

jobs:
  automerge:
    if: |
      github.actor == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, 'ready-to-merge') && startsWith(github.event.pull_request.head.sha, github.event.pull_request.head.repo.owner.login == 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set PR_NUMBER env var
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        shell: bash
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Remove ready-for-merge label
        run: gh pr edit "$PR_NUMBER" --remove-label "ready-to-merge"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      - name: Add auto-merged label
        run: gh pr edit "$PR_NUMBER" --add-label "auto-merged"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
