name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Enable auto-merge for Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
