name: Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint (biome)
        run: |
          if [ -f biome.json ]; then npx biome check .; else echo 'No biome config'; fi
