name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Install ajv-cli
        run: npm install -g ajv-cli
      - name: Run PowerShell app checks
        shell: pwsh
        run: pwsh .github/scripts/test-apps.ps1
